server {
    listen 6070;
    root ./www;
	client_max_body_size 100;

    location /images {
        root ./assets;

    }
    location /contacts {
	root ./database;

    }
	
	location /cgi {
        root ./cgi-bin;
        cgi .py /usr/bin/python3;
	}

    location /upload {
	root ./assets;

    }
}
