server {
    listen 6070;
    root ./www;
	client_max_body_size 1000;

    location /images {
        root ./assets;

    }
    location /contacts {
	root ./database;

    }
	
	location /cgi {
# cgi .py;
	}

    location /upload {
	root ./assets;

    }
}
