server {
    listen 6060;
    listen 7060;
    root ./www;

    location /images {
        root ./assets;

    }

}

server {
    listen 8060;
    root ./www;

    location /images {
        root ./assets;

    }

}
