server {
    listen 127.0.0.1:8080;
    server_name localhost webserv.local;
    root ./www;
    client_max_body_size 120000000;

    error_page 400 ./errors/400.html;
    error_page 403 ./errors/403.html;
    error_page 404 ./errors/404.html;
    error_page 405 ./errors/405.html;
    error_page 413 ./errors/413.html;
    error_page 500 ./errors/500.html;
    error_page 501 ./errors/501.html;

    location /folder {
        root ./folder;
        autoindex on;
    }
    location /images {
        root ./assets;
        methods GET;
    }
    location /old {
        return 301 /;
    }
    location /cgi {
        root ./cgi-bin;
        cgi .py /usr/bin/python3;
    }
    location /upload {
        root ./uploads;
        upload off;
        upload_path ./www/uploads;
        index index.html;
    }
}

# Second bloc virtuel sur le MEME host:port que le premier.
# Selectionne uniquement quand le header Host vaut "other.local".
server {
    listen 127.0.0.1:8080;
    server_name other.local;
    root ./www;

    location / {
        return 302 http://localhost:8080/;
    }
}

server {
    listen 127.0.0.1:8081;
    root ./www;
    client_max_body_size 1000000;
    error_page 404 ./errors/404.html;

    location /cgi {
        root ./cgi-bin;
        cgi .py /usr/bin/python3;
    }
}
